services:
  - type: web
    name: saturday-run-coffee-club
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - saturday-run-coffee.onrender.com
